### PR TITLE
Allow doctrine/collections v2

### PR DESCRIPTION
**Pull request by wouter90**
I removed the composer.lock file too. The lock file should not be present in a library.

### CODE REVIEW

**Comment by Steart** [comment]
Would be great if this could be merged, because it is blocking!

**Comment by reyostallenberg** [comment]
How is an addition by a library this library doesn't depend on a fix of a 'blocking' problem

**Comment by reyostallenberg** [comment]
Why are you adding this dependency? As it is not needed by the library

What error or issue is causing the lock file in your application?
Even composer itself writes about it https://getcomposer.org/doc/02-libraries.md#lock-file

> Lock file
> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.
> If you do not want to commit the lock file, and you are using git, add it to the .gitignore.

**Comment by wouter90** [comment]
> Why are you adding this dependency? As it is not needed by the library
> 
> What error or issue is causing the lock file in your application? Even composer itself writes about it https://getcomposer.org/doc/02-libraries.md#lock-file
> 
> > Lock file
> > For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.
> > If you do not want to commit the lock file, and you are using git, add it to the .gitignore.

My bad, I totally did this PR wrong. I wanted to allow doctrine/collections v2 instead of annotations. Was working on upgrading both libraries in some projects and mixed them up somehow.

For the lock file; I removed it because it was not up to date with composer.json in the first place and I always learned that a lock file should not exist in a library.

**Comment by reyostallenberg** [comment]
Thanks for your PR. 

Our upstream process is managed differently because we want to generate 'downgraded' code to support older PHP versions but also release a modern PHP package.
Therefor I've added your proposed changes myself in https://github.com/flowmailer/flowmailer-php-sdk/commit/938ef368b215b5cb7ba1dd742958d077cd67b11d

Your problems should be fixed by requiring flowmailer/flowmailer-php-sdk:^1.5

**Comment by wouter90** [comment]
Thanks for the merge. I'll update our code accordingly.

**Pull request closed without merging**
